version = 1

test_patterns = [
  "tests/**"
]

exclude_patterns = [
  "baseframe/static/**"
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"

[analyzers.meta]
max_line_length = 100
